package com.datou.springstudy.dal.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iduser
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    private Integer iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iduser
     *
     * @return the value of user.iduser
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iduser
     *
     * @param iduser the value for user.iduser
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbggenerated Sat Apr 30 18:29:48 CST 2016
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}